//This file is automatically generated. DO NOT EDIT!

#include <RobotRaconteur.h>
#include <boost/signals2.hpp>
#pragma once

namespace edu
{
namespace rpi
{
namespace robotics
{
namespace abb
{
namespace egm
{

class EGM;

class EGM : public virtual RobotRaconteur::RRObject
{
public:
virtual RR_SHARED_PTR<RobotRaconteur::RRArray<double > > get_joint_angle()=0;
virtual void set_joint_angle(RR_SHARED_PTR<RobotRaconteur::RRArray<double > > value)=0;

virtual RR_SHARED_PTR<RobotRaconteur::RRArray<double > > get_joint_angle_setpoint()=0;
virtual void set_joint_angle_setpoint(RR_SHARED_PTR<RobotRaconteur::RRArray<double > > value)=0;

virtual std::string RRType() {return "edu.rpi.robotics.abb.egm.EGM";  }
};

}
}
}
}
}

