//This file is automatically generated. DO NOT EDIT!

#include <RobotRaconteur.h>
#include <boost/signals2.hpp>
#pragma once

namespace example
{
namespace RR_EGM
{

class IRB6640;

class IRB6640 : public virtual RobotRaconteur::RRObject
{
public:
virtual void setjoints(RR_SHARED_PTR<RobotRaconteur::RRArray<double > > joint)=0;

virtual RR_SHARED_PTR<RobotRaconteur::RRArray<double > > readjoints()=0;

virtual std::string RRType() {return "example.RR_EGM.IRB6640";  }
};

}
}

